### ISSUE TITLE
Party items

### ISSUE THREAD

**Issue by pburkholder** [gathertown/mapmaking#3]
I had a bunch of friends to my space on Saturday and we had a blast of a time -- really the only fun I've had with old friends in nearly a year. Thanks for your terrific platform.  

That said, I'd love to have for my next party:

* bar
* barstools
* wine glasses
* beer bottles
* cocktail glasses
* wine bottles

Our party was in a re-creation of our high school, so if I could I'd turn the teacher's lounge into a hookah bar, so -- how about a hookah?

Thanks!

**Comment by nostalgiapurgatory** [comment]
Peter, thanks for your suggestions! We recently added bar and counter items to our new object picker. I hope you like them. :) Here is a Wish List to add objects that would be useful to you for your events and spaces!
https://docs.google.com/document/d/1-SNDgiq-9Ynj2T6O65D7RlKSFwa0h8swgFbbS-yxWYA/edit

**Comment by twostripe** [comment]
Circling back on this way later. We now have many of these items, and future item requests should be added to [The Object Wishlist Google Doc](https://docs.google.com/document/d/1-SNDgiq-9Ynj2T6O65D7RlKSFwa0h8swgFbbS-yxWYA/edit)
