### ISSUE TITLE
How do we upload tilesets to GatherTown?

### ISSUE THREAD

**Issue by tompollard** [gathertown/mapmaking#6]
Please could someone point me to some documentation that explains how resources in the [tilesets folder](https://github.com/gathertown/mapmaking/tree/master/tilesets) can be uploaded to GatherTown? For example, if we wanted to upload the [space themed tiles](https://github.com/gathertown/mapmaking/blob/master/tilesets/space%20tiles.png), how would we do this?

As far as I can see, the object uploader requires each object to be uploaded individually. To use this tool, presumably we would need to cut the tileset into 32x32px chunks and then upload them one by one? Is there an easier alternative?  

![Screen Shot 2021-03-26 at 11 46 26](https://user-images.githubusercontent.com/822601/112657540-e8c51c00-8e28-11eb-870e-925644e35614.png)

**Comment by Klinshy** [comment]
I recommend using Software like "Tiled" and "Gimp" to create the Background for you Gather.

**Comment by tompollard** [comment]
Thanks @Klinshy. Sounds like the answer is that there's no alternative to uploading objects one-by-one at the moment. I'll close the issue.
