### ISSUE TITLE
can we know how you draw these maps

### ISSUE THREAD

**Issue by xuzeshen** [gathertown/mapmaking#8]
develop by your team self or use some canvas game lib?  thank you ^_^

**Comment by despokd** [comment]
Have al look at
 [Custom map creation overview](https://support.gather.town/help/custom-map-creation-overview)

**Comment by xuzeshen** [comment]
Wow, that's Tiled. Thank you so much. Then there is another problem, since you choose Tiled, as a front-end developer, is there some suitable javascript canvas lib just use in Gather to draw these maps to users?

**Comment by despokd** [comment]
I use Tiled to draw my maps. What do you expect from a JS Lib?

**Comment by twostripe** [comment]
This is the art/map arm of the company Gather (gather.town). We have a custom game engine that renders these maps "in game".

We also use Tiled to create a lot of the base backgrounds for these maps, and Gather's online Mapmaker tool to add additional objects.

Closing this issue 👍

**Comment by xuzeshen** [comment]
@twostripe Thank you for your comprehensive answer.
